### PR TITLE
fix: add explorer urls to externalAllowlist

### LINKED ISSUE #68: [Task]: Alphanet explorer link does not open
### Task description

The link to consult the explorer does not open

### PR DESCRIPTION
**Pull request by cpl121**
Closes #68

## Summary
Add explorer urls to externalAllowlist

### Changelog
```
Add explorer urls to externalAllowlist
```

## Type of Change
Please select any type below that is applicable to your changes, and delete those that are not.
- [ ] __Breaking__ - any change that would cause existing functionality to not work as expected
- [ ] __Chore__ - refactoring, build scripts or anything else that isn't user-facing
- [ ] __Docs__ - changes to the documentation
- [X] __Fix__ - a change which fixes an issue
- [ ] __New__ - a change which implements a new feature
- [ ] __Update__ - a change which updates existing functionality

### Platforms
Please select any platforms where your changes have been tested.
- __Desktop__
	- [ ] MacOS
	- [X] Linux
	- [ ] Windows

## Checklist
Please tick all of the following boxes that are relevant to your changes, and delete those that are not.
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/desktop/electron/main.js [hunk 1]
```diff
@@ -185,6 +185,8 @@ function isUrlAllowed(targetUrl) {
         'explorer.iota.org',
         'iotatreasury.org',
         'govern.iota.org',
+        'explorer.iota-alphanet.iotaledger.net',
+        'explorer.stardust-mainnet.iotaledger.net',
```
Comment (begonaalvarezd) [inline packages/desktop/electron/main.js:189]: Is this link needed? Wouldnt it be enough linking to the production explorer `explorer.iota.org`

**Review by brancoder — APPROVED** [review]
LGTM

**Review by begonaalvarezd — APPROVED** [review]
